### ISSUE TITLE
loader.rb:65: syntax error, unexpected ')', expecting ']'

### ISSUE THREAD

**Issue by cgendreau** [dshorthouse/dina-image-upload#2]
https://github.com/dshorthouse/dina-image-upload/blob/d9ddc3a0a3e784ac405a6c4b15e0140d344f7c26/loader.rb#L65

`error = File.join(Dir.pwd, 'errors', clean_dirname(OPTIONS[:directory) + "-errors.txt")`

should probably be

`error = File.join(Dir.pwd, 'errors', clean_dirname(OPTIONS[:directory]) + "-errors.txt")`

**Comment by dshorthouse** [comment]
Argh. Serves me right for trying to copy/paste.
